/* ============================================================================
 *  PROJECT 90 — Banco de perguntas do "Pergunta do dia" (diário)
 *
 *  A pergunta de cada dia é escolhida de forma DETERMINÍSTICA pelo número do
 *  dia do desafio: bank[(dia - 1) % bank.length] — ver promptForDay() em
 *  diario.html.
 *
 *  IMPORTANTE: não reordene nem remova itens. Só acrescente no fim — se a
 *  ordem mudar, os dias já respondidos passam a exibir outra pergunta.
 *
 *  São 92 perguntas: cobre os 90 dias do desafio sem repetir.
 * ========================================================================== */
window.P90_JOURNAL_PROMPTS = [
  'Qual foi o momento mais difícil de hoje e como você reagiu a ele?',
  'O que te deu energia hoje? E o que te drenou?',
  'Que decisão pequena de hoje o seu "eu de daqui a um ano" agradeceria?',
  'Onde você quase desistiu hoje — e o que te fez continuar?',
  'Que hábito hoje pareceu leve, quase automático? O que mudou?',
  'De que você teve medo hoje, mesmo que ninguém tenha percebido?',
  'Qual foi a coisa mais gentil que você fez hoje — para outra pessoa ou para si?',
  'O que você adiou hoje? Por quê, de verdade?',
  'Qual conversa de hoje ficou na sua cabeça, e o que ela está te dizendo?',
  'Se hoje fosse um capítulo de um livro sobre a sua vida, qual seria o título?',
  'O que você fez hoje só porque era mais confortável, não porque era certo?',
  'Que parte do seu dia você faria de novo exatamente igual?',
  'Onde você foi mais duro consigo mesmo do que seria com um amigo?',
  'Que pensamento se repetiu na sua cabeça hoje? Ele te serve?',
  'O que hoje te lembrou de quem você quer se tornar?',
  'Qual foi o maior desperdício de tempo de hoje — e o que havia por trás dele?',
  'Você disse "sim" para algo hoje que devia ter sido "não"? Ou o contrário?',
  'Que emoção você tentou empurrar para debaixo do tapete hoje?',
  'O que você aprendeu hoje que não sabia ontem?',
  'Qual pessoa você admirou hoje, e por qual qualidade específica?',
  'Onde você sentiu orgulho de si hoje, mesmo numa coisa pequena?',
  'O que o seu corpo estava tentando te dizer hoje que você ignorou?',
  'Se você pudesse repetir cinco minutos de hoje, quais seriam?',
  'Que promessa você fez a si mesmo recentemente? Como está indo?',
  'O que hoje te tirou do piloto automático?',
  'Qual foi a fricção entre o que você planejou e o que aconteceu?',
  'Você foi mais reativo ou mais intencional hoje? Dê um exemplo.',
  'O que você está evitando pensar a respeito nesta semana?',
  'Que elogio você recebeu e não conseguiu aceitar direito?',
  'Qual foi a escolha mais alinhada com os seus valores hoje?',
  'O que te deixou irritado hoje — e o que isso revela sobre o que você valoriza?',
  'Se ninguém fosse julgar, o que você teria feito diferente hoje?',
  'Qual foi o instante de hoje em que você se sentiu mais vivo?',
  'O que você fez hoje que o seu "eu de cinco anos atrás" acharia impossível?',
  'Onde a pressa te atrapalhou hoje?',
  'Que limite você precisou colocar hoje — e conseguiu?',
  'O que te fez sorrir sem querer hoje?',
  'Qual medo antigo apareceu hoje disfarçado de outra coisa?',
  'O que você agradeceria hoje que normalmente passa despercebido?',
  'Em que momento de hoje você se sentiu no controle?',
  'O que você fez hoje por hábito e já não faz mais sentido?',
  'Qual foi a coisa mais honesta que você disse hoje?',
  'Onde você se comparou com alguém hoje, e como isso te afetou?',
  'O que hoje exigiu coragem, mesmo que pequena?',
  'Que padrão seu você reconheceu hoje se repetindo?',
  'Se hoje tivesse uma trilha sonora, que música seria?',
  'O que você fez hoje só para agradar os outros?',
  'Qual foi o pensamento mais generoso que você teve sobre si mesmo?',
  'O que te deu paz hoje, mesmo que por poucos minutos?',
  'Onde você poderia ter pedido ajuda e não pediu?',
  'Que verdade sobre você ficou mais clara hoje?',
  'O que você faria amanhã se soubesse que não pode falhar?',
  'Qual foi o esforço invisível de hoje que ninguém vai ver?',
  'O que você deixou para trás hoje — um hábito, uma ideia, um peso?',
  'Em que você foi corajoso sem perceber na hora?',
  'Qual foi a parte mais chata do dia, e ela era mesmo necessária?',
  'O que hoje te fez sentir grato por estar exatamente onde está?',
  'Que conselho você daria hoje para si mesmo de ontem?',
  'Onde você foi paciente hoje quando teria sido fácil não ser?',
  'O que te distraiu do que realmente importava hoje?',
  'Qual foi a pequena vitória que você quase deixou passar batido?',
  'O que você sentiu falta de fazer hoje?',
  'Se você tivesse que resumir o dia em uma palavra, qual seria — e por quê?',
  'O que hoje te mostrou que você está mudando?',
  'Que desconforto de hoje foi, no fundo, crescimento?',
  'O que você faria com uma hora a mais hoje?',
  'Qual relação na sua vida precisa de mais atenção agora?',
  'O que você fez hoje que estava alinhado com a pessoa que você quer ser daqui a 90 dias?',
  'Onde você sentiu inveja hoje — e o que isso aponta que você quer?',
  'Qual foi o momento de hoje em que você se orgulhou de não ter reagido?',
  'O que você aprendeu hoje sobre os seus limites?',
  'Que coisa boa aconteceu hoje que você não planejou?',
  'O que você está pronto para parar de carregar?',
  'Onde você foi fiel a um compromisso mesmo sem vontade?',
  'Qual foi a decisão mais difícil de hoje, mesmo que pequena?',
  'O que hoje te deu esperança sobre a sua direção?',
  'Que hábito, se você mantivesse por mais 60 dias, mudaria a sua vida?',
  'O que você percebeu hoje que estava sentindo o dia inteiro?',
  'Onde você se subestimou hoje?',
  'O que você faria hoje de novo se pudesse, sem mudar nada?',
  'Qual foi a coisa mais difícil de admitir para si mesmo hoje?',
  'O que te fez sentir conectado a alguém hoje?',
  'Que parte de hoje você quer levar para amanhã?',
  'Onde a sua rotina te protegeu de um dia ruim hoje?',
  'O que você fez hoje que exigiu disciplina em vez de motivação?',
  'Qual foi o pensamento que te puxou para baixo — e ele era verdade?',
  'O que você celebraria hoje se fosse mais fácil se dar crédito?',
  'Que pergunta você tem evitado se fazer ultimamente?',
  'O que hoje te fez desacelerar, e por que isso foi bom?',
  'Onde você escolheu o caminho mais longo e mais certo hoje?',
  'O que você quer que seja diferente amanhã — e qual é o primeiro passo?',
  'Olhando para o dia inteiro: do que você mais se orgulha?',
];
