/* ═══════════════════════════════════════════════
   PROJECT 90 — FRASES DE EFEITO
   Estilo Jordan Peterson: responsabilidade, ordem e caos, sentido,
   sofrimento voluntário, a pessoa que você poderia ser, mudar de vida
   de verdade. Uma frase aleatória é mostrada no dashboard a cada load.
═══════════════════════════════════════════════ */
window.P90_QUOTES = [
  "Você não muda quando entende que precisa. Você muda quando não suporta mais continuar o mesmo.",
  "A pessoa que você poderia ser está esperando você decidir que ela vale o esforço.",
  "Ninguém vem te resgatar. A má notícia é essa. A boa é que, então, sobrou para você.",
  "Todo dia que você adia a mudança, você vota na versão de si que menos respeita.",
  "A transformação começa no instante em que você para de negociar com a própria mediocridade.",
  "Você já sabe o que precisa fazer. O problema nunca foi ignorância. Foi coragem.",
  "Compare-se com quem você era ontem, não com quem outra pessoa é hoje.",
  "Levante a cabeça, alinhe os ombros e encare o peso que é seu carregar.",
  "Ponha sua própria casa em ordem impecável antes de criticar o mundo.",
  "Trate a si mesmo como alguém por quem você é responsável.",
  "Diga a verdade. Ou, no mínimo, não minta.",
  "Persiga o que tem sentido, não o que é conveniente.",
  "A vida é sofrimento. A pergunta não é como evitá-lo, é o que fazer com ele.",
  "Você é mais forte do que imagina e mais responsável do que gostaria.",
  "O caos é o território que você ainda não domina. A ordem é o que já conquistou. Fique com um pé em cada.",
  "O sentido aparece na fronteira entre a ordem e o caos, exatamente onde você tem medo de pisar.",
  "Adote a responsabilidade máxima que você consegue suportar. É ela que dá peso à sua vida.",
  "Um fardo carregado de propósito é mais leve do que uma vida sem fardo nenhum.",
  "Não é o mundo que precisa mudar primeiro. É você.",
  "A disciplina não te aprisiona. Ela é a única coisa que te liberta.",
  "Cada hábito que você mantém é um voto de confiança na pessoa que você está construindo.",
  "O ressentimento é veneno. Ou você tem algo a dizer, ou algo a amadurecer.",
  "Você não é quem diz que quer ser. Você é o que faz todos os dias.",
  "A pessoa que desiste no dia 3 e a que chega no dia 90 tomaram a mesma decisão. Uma só a manteve.",
  "Escolha voluntariamente o peso, antes que a vida escolha por você e sem aviso.",
  "Fale com precisão. O que não é nomeado te governa nas sombras.",
  "Aponte para o mais alto que você consegue conceber e caminhe nessa direção.",
  "Não confunda o que é fácil com o que é bom. Quase nunca são a mesma coisa.",
  "A vida que você inveja foi construída nos dias em que ninguém estava olhando.",
  "Você tem exatamente a vida que suas decisões diárias sustentam. Mude as decisões.",
  "Arrume a cama. Não porque é pouco, mas porque é o primeiro tijolo do dia.",
  "A ordem no seu quarto é a prova de que você consegue impor ordem em algum lugar. Comece por aí.",
  "O que você não enfrenta hoje volta amanhã maior e mais caro.",
  "Ninguém constrói uma catedral num dia, mas ninguém constrói uma sem colocar a pedra de hoje.",
  "Você não precisa acreditar que vai dar certo. Precisa apenas fazer a próxima coisa certa.",
  "A motivação te tira da cama uma vez. A rotina te tira todos os outros dias.",
  "Você não afoga no primeiro gole de água. Você afoga quando para de nadar.",
  "O futuro chega de qualquer jeito. A pergunta é se você chega junto ou arrastado.",
  "Há um preço para mudar e um preço para não mudar. O segundo é pago em arrependimento.",
  "Assuma que a pessoa à sua frente sabe algo que você não sabe. Ouça como quem tem o que aprender.",
  "Você não conserta o mundo com raiva. Você conserta a si mesmo com trabalho.",
  "O sofrimento sem sentido destrói. O sofrimento com direção constrói.",
  "Não peça uma vida mais leve. Peça ombros mais fortes.",
  "A liberdade sem estrutura não é liberdade, é deriva.",
  "Quando você não sabe para onde ir, qualquer desculpa serve de bússola.",
  "Coragem não é ausência de medo. É agir enquanto o medo grita para você parar.",
  "Você tem cem motivos para não começar hoje. Precisa de apenas um para começar.",
  "O que você tolera define o teto da sua vida.",
  "Não se compare com o pico dos outros usando o seu pior dia como régua.",
  "Enfrente o dragão enquanto ele é pequeno. Ele só cresce enquanto você espera.",
  "A pessoa que você quer ser não faz o que você está prestes a não fazer.",
  "Todo grande erro começou como uma pequena concessão que você achou que não contava.",
  "A vida cobra juros de tudo que você posterga.",
  "Ninguém respeita quem não cumpre a palavra que deu a si mesmo.",
  "Você não precisa de mais informação. Precisa parar de fugir da que já tem.",
  "O caminho fácil hoje é o caminho difícil amanhã, só que sem volta.",
  "Domine algo pequeno por completo antes de reclamar do que é grande.",
  "A ordem que você constrói dentro de casa é o único lugar de onde você pode encarar o caos lá fora.",
  "Sua palavra vale o quanto ela custa a você para ser mantida.",
  "Não espere se sentir pronto. Ninguém nunca se sentiu. Comece assim mesmo.",
  "O que você faz quando ninguém vê é quem você é de verdade.",
  "Você carrega o mundo nas costas. Escolha carregar de pé.",
  "Cada dia é um voto. Você está votando em quem?",
  "O arrependimento pesa mais que a disciplina. Escolha o peso mais barato.",
  "A pessoa disciplinada de amanhã é feita das escolhas chatas de hoje.",
  "Você não precisa ser perfeito. Precisa ser um pouco menos covarde do que ontem.",
  "O abismo que você evita olhar é o mesmo que engole quem nunca olha.",
  "Aponte para algo tão alto que exija o seu melhor todos os dias para chegar perto.",
  "O sentido não é encontrado. É construído, tijolo por tijolo, escolha por escolha.",
  "Se a sua vida não tem peso, é porque você recusou toda responsabilidade que podia ter assumido.",
  "A mudança verdadeira é chata por fora e revolucionária por dentro.",
  "Você já foi arrastado pela correnteza o suficiente. Hoje você nada.",
  "O primeiro passo não muda sua vida. Ele muda quem dá o segundo.",
  "Não confunda conforto com paz. Um te adormece, o outro te sustenta.",
  "A vida não te deve facilidade. Deve a você a chance de se tornar capaz.",
  "Você não é vítima da sua história. É o autor do próximo capítulo.",
  "Quem não decide para onde vai é levado para onde não quer estar.",
  "A pessoa que você admira também teve o dia em que quis desistir. Ela só não desistiu.",
  "O peso da responsabilidade é o antídoto contra o vazio de não ter nenhuma.",
  "Comece pequeno. Comece feio. Mas comece hoje, porque amanhã custa mais.",
  "Você tem dentro de si tanto o herói quanto o covarde. A rotina decide qual alimentar.",
  "O caos vai testar sua ordem. Construa uma ordem que aguente o teste.",
  "Não minta para si mesmo sobre o que você quer. A vida inteira depende dessa honestidade.",
  "A liberdade que você tanto quer está escondida atrás da rotina que você tanto evita.",
  "Cada promessa quebrada com você mesmo enfraquece a próxima que você fizer.",
  "Você não precisa de sorte. Precisa de repetição.",
  "O dia em que você não sente vontade é o dia que separa quem muda de quem só fala.",
  "Não existe versão da sua vida melhor sem uma versão de você mais forte.",
  "A dor de disciplinar-se dura minutos. A dor de se decepcionar dura anos.",
  "Você é livre para escolher suas ações, não para escolher as consequências delas.",
  "Ninguém constrói caráter em dias fáceis. Agradeça aos difíceis.",
  "A pessoa que você poderia ser está a exatamente noventa dias de decisões daqui.",
  "O medo aponta com precisão para onde você precisa ir.",
  "Você não muda o passado. Mas cada hábito de hoje reescreve o significado dele.",
  "Não peça menos caos. Torne-se alguém que impõe ordem.",
  "A vida boa não é a sem tempestade. É a com um alicerce que não cede.",
  "Toda desculpa que você aceita hoje vira uma corrente amanhã.",
  "O que você chama de falta de tempo costuma ser falta de hierarquia.",
  "Cuide do seu corpo como quem empresta ele para o futuro e vai ter que devolver.",
  "Você não se torna confiável de repente. Você se torna confiável um dia de cada vez.",
  "O caminho para fora do inferno é através, nunca ao redor.",
  "Se você não aguenta a versão difícil de hoje, não vai aguentar a versão cara de depois.",
  "A ordem que você não constrói é a bagunça que você herda.",
  "Você não precisa ganhar todos os dias. Precisa não abandonar nenhum.",
  "O sentido pesa. E é justamente o peso que impede sua vida de voar sem rumo.",
  "Não terceirize sua vida para as circunstâncias. Assuma a autoria.",
  "A pessoa que você quer ser não está esperando condições perfeitas.",
  "Cada dia registrado é uma pedra numa parede que ninguém pode derrubar depois.",
  "Você não é o que sente. Você é o que faz apesar do que sente.",
  "A comparação com os outros rouba. A comparação com o seu ontem constrói.",
  "O trabalho chato de hoje é o privilégio de quem não quis o resultado o suficiente ontem.",
  "Não se pergunte se você merece uma vida melhor. Pergunte se você está disposto a pagá-la.",
  "A rotina é a forma como o futuro entra na sua vida antes de chegar.",
  "Você tem uma dívida com a pessoa que poderia ter sido. Comece a quitá-la hoje.",
  "O caos não pede licença. Só uma ordem interna forte segura o baque.",
  "Assuma responsabilidade até por aquilo que não foi culpa sua. É assim que se ganha poder sobre a própria vida.",
  "Não espere o incêndio para aprender a carregar água.",
  "A verdade dita hoje dói menos que a mentira mantida por dez anos.",
  "Você não precisa de permissão para se tornar quem deveria ser.",
  "O que você repete vira quem você é. Escolha melhor o que repetir.",
  "A vida vai te dar exatamente o tamanho de fardo que ela achar que você aguenta. Aguente mais.",
  "Não há transformação sem desconforto. O desconforto é o sinal de que está funcionando.",
  "Você já perdeu tempo suficiente sendo espectador da própria vida.",
  "A pessoa forte não é a que nunca cai. É a que já decidiu como vai levantar.",
  "Se você não define a sua direção, a preguiça define por você.",
  "Cada dia sem hábito é um dia em que o caos avançou de graça.",
  "O respeito próprio é construído com atos, não com afirmações.",
  "Você não vence o dia de hoje. Você o honra, e segue.",
  "A vida de quem você inveja custou coisas que você ainda não quis pagar.",
  "Não existe fundo do poço que a repetição de bons hábitos não comece a escavar para cima.",
  "O caos que você não organiza vira a rotina que você suporta.",
  "Aponte alto o suficiente para que falhar já valha a pena.",
  "Você é o adulto responsável pela criança que você foi e pelo velho que você vai ser.",
  "A disciplina é amor próprio traduzido em ação.",
  "Não pergunte por que a vida é dura. Pergunte quem você vira ao carregá-la.",
  "O primeiro dia é sobre coragem. Todos os outros são sobre caráter.",
  "Você não precisa acreditar em si mesmo. Precisa apenas não trair sua palavra hoje.",
  "A mudança que dura é feita de dias sem graça repetidos com teimosia.",
  "O que você adia com medo, você paga com juros de vergonha.",
  "Ordene o que está ao seu alcance. É de lá que se enfrenta o resto.",
  "Você não é o resultado das suas intenções. É o resultado das suas repetições.",
  "A pessoa que você poderia ser julga silenciosamente cada desculpa que você dá.",
  "Não fuja do peso. Fugir dele é o que te deixa fraco.",
  "A vida cobra caro de quem não escolhe. Escolha antes que ela cobre.",
  "Você tem noventa dias para provar a si mesmo que a sua palavra vale alguma coisa.",
  "O caminho da mudança é estreito, íngreme e vazio de plateia. Ande assim mesmo.",
  "Não se trata de nunca falhar. Trata-se de nunca abandonar.",
  "O sentido da sua vida está do outro lado das coisas que você está evitando.",
  "Você não precisa de um novo plano. Precisa executar o que já sabe.",
  "A ordem interior é a única fortaleza que o caos exterior não invade.",
  "Cada hábito mantido é uma promessa cumprida com quem você quer se tornar.",
  "Não terceirize sua salvação. A conta é sua e a caneta também.",
  "Você já tentou a versão preguiçosa da sua vida. Como foi?",
  "A vida boa não é ausência de dragões. É ter aprendido a caçá-los.",
  "O peso que você recusa hoje não desaparece. Ele só encontra alguém mais fraco para carregar: o seu eu de amanhã.",
  "Você não deve à vida o seu potencial. Você deve a si mesmo.",
  "O medo de começar é menor que a vergonha de nunca ter tentado.",
  "Ninguém te deve motivação diária. Você se deve consistência diária.",
  "A pessoa que muda de verdade fica entediada de tanta repetição, e continua.",
  "O que você faz nos dias ruins define o tamanho da vida que você pode ter nos bons.",
  "Não espere o mundo ficar justo para começar a se tornar forte.",
  "A verdade sobre a sua vida cabe nos seus últimos sete dias. Olhe para eles.",
  "Você não precisa de coragem para o ano inteiro. Precisa dela só para hoje.",
  "A mudança começa quando o custo de continuar igual finalmente supera o medo de agir.",
  "Toda vida grande foi antes uma sequência absurda de dias comuns bem vividos.",
  "O caos vai bater à porta. Que ele encontre alguém em pé.",
  "Aponte para o bem mais alto e deixe que ele reorganize tudo abaixo dele.",
  "Você é responsável não só pelo que faz, mas pelo que permite virar hábito.",
  "A disciplina de hoje é a autoestima de daqui a um ano.",
  "Não pergunte se vai ser difícil. Vai. Pergunte se vai valer. Vale.",
  "O primeiro passo assusta porque revela quantos outros existem. Dê mesmo assim.",
  "Você não vira outra pessoa. Você vira, enfim, você mesmo.",
  "A comparação para cima paralisa. A comparação com seu ontem impulsiona.",
  "O trabalho invisível de hoje é o resultado inegável de amanhã.",
  "Não se pergunte o que a vida te deve. Pergunte o que você ainda não entregou.",
  "A rotina é a maneira mais barata de comprar a pessoa que você quer ser.",
  "Você tem uma promessa em aberto com quem poderia ter sido. Comece a pagar.",
  "O caos externo só derruba quem não tem coluna interna.",
  "Assuma o fardo até dos erros alheios. É assim que se conquista domínio sobre a própria história.",
  "Não espere a crise para descobrir do que você é feito.",
  "Mentir para si mesmo é a única fraude da qual você nunca escapa.",
  "Você não precisa da aprovação de ninguém para se tornar quem deveria ser.",
  "O que se repete constrói. O que se abandona apodrece. Escolha o que regar.",
  "A vida sobe a régua conforme você cresce. Prefira crescer a abaixar a régua.",
  "Sem desconforto não há mudança. O desconforto é o recibo do progresso.",
  "Você já assistiu à sua vida de fora tempo demais. Entre em campo.",
  "O forte não é o que nunca hesita. É o que já decidiu o que fazer depois de hesitar.",
  "Se você não escolhe seu norte, a inércia escolhe o abismo.",
  "Cada dia sem esforço é território entregue de graça ao caos.",
  "Respeito próprio não se declara. Se acumula, ato por ato.",
  "Você não conquista o dia. Você o honra e passa para o próximo.",
  "A vida que você admira foi paga em moedas que você ainda hesita em gastar.",
  "Não existe buraco tão fundo que a repetição paciente de bons hábitos não comece a preencher.",
  "O caos que você ignora hoje vira a normalidade que você lamenta amanhã.",
  "Mire tão alto que até a falha te deixe num lugar melhor.",
  "Você é o responsável pela criança que foi e pelo velho que será. Aja como tal.",
  "Disciplina é o nome que se dá ao amor próprio quando ele vira hábito.",
  "Não pergunte por que a vida pesa. Pergunte quem você vira sob o peso.",
  "O dia um exige coragem. Os oitenta e nove seguintes exigem caráter.",
  "Você não precisa acreditar no resultado. Precisa não trair a próxima ação.",
  "A mudança que dura tem cara de tédio e alma de revolução.",
  "O que você adia por medo, você quita em vergonha, com juros.",
  "Coloque em ordem o que está ao seu alcance. É o único ponto de onde se enfrenta o resto.",
  "Você não é a soma das suas intenções. É a soma das suas terças-feiras.",
  "A pessoa que você poderia ser observa em silêncio cada saída fácil que você escolhe.",
  "Não se afaste do peso. É ele que endireita a sua coluna.",
  "A vida cobra caro de quem não decide. Decida antes que a fatura chegue.",
  "Noventa dias para provar a si mesmo que a sua palavra tem lastro.",
  "O caminho da transformação é estreito, íngreme e sem público. Trilhe assim mesmo.",
  "Não é sobre nunca cair. É sobre nunca ficar caído.",
  "O sentido que você procura está guardado exatamente onde você tem medo de procurar.",
  "Você não precisa de um plano novo. Precisa executar o velho sem pena de si.",
  "A ordem que você cultiva por dentro é a muralha que o caos de fora não atravessa.",
  "Cada hábito honrado é uma promessa cumprida com o seu eu futuro.",
  "A conta da sua vida é sua. A caneta que a escreve também.",
  "Você já experimentou a versão frouxa de si. Não deu certo. Tente a versão dura.",
  "Vida boa não é a que não tem monstros. É a de quem aprendeu a caçá-los.",
  "O fardo que você recusa hoje vai cair sobre alguém mais fraco: você, amanhã.",
  "Você não deve o seu melhor ao mundo. Deve a si mesmo, e a dívida vence hoje.",
  "O medo de começar é sempre menor que o peso de nunca ter começado.",
  "Ninguém te deve empolgação todo dia. Você se deve presença todo dia.",
  "Quem muda de verdade cansa da repetição muito antes de parar de repetir.",
  "O que você faz no pior dia da semana define o teto da sua melhor versão.",
  "Não espere o mundo ficar justo para você ficar forte.",
  "A verdade sobre você está nos seus últimos sete dias. Tenha coragem de olhar.",
  "Você não precisa de coragem para o desafio inteiro. Só para as próximas horas.",
  "A mudança nasce quando permanecer igual finalmente custa mais caro do que agir.",
  "Toda vida notável foi, antes, uma pilha teimosa de dias sem graça.",
  "O caos vai bater na sua porta. Que ele encontre você de pé, não de joelhos.",
  "Mire no bem mais alto que consegue imaginar e deixe que ele arrume o resto.",
  "Você responde não só pelo que faz, mas por aquilo que deixa virar rotina.",
  "A disciplina de hoje é a paz de espírito de daqui a um ano.",
  "Vai ser difícil, sim. A pergunta certa é se vai valer. E vai.",
  "Você não se transforma em outro. Você para de trair quem sempre foi por dentro.",
  "Trabalho que ninguém vê hoje vira resultado que ninguém nega amanhã.",
  "Não pergunte o que a vida te deve. Pergunte o que você ainda não entregou a ela.",
  "A rotina é o jeito mais barato de comprar a pessoa que você quer ser.",
  "O caos lá fora só derruba quem não ergueu nada por dentro.",
  "Carregue até o erro do outro nas costas. É assim que se toma as rédeas da própria vida.",
  "Não espere a tempestade para descobrir se o seu alicerce presta.",
  "Enganar a si mesmo é a única fraude da qual você nunca sai impune.",
  "Você não precisa que ninguém autorize a sua transformação.",
  "O que se repete floresce. O que se larga apodrece. Cuide do que quer colher.",
  "A vida ergue a régua na mesma medida em que você cresce. Prefira crescer.",
  "O progresso mora do lado desconfortável de cada decisão.",
  "Chega de assistir. A sua vida está acontecendo com ou sem a sua participação.",
  "O forte hesita como todo mundo. A diferença é o que ele faz três segundos depois.",
  "Sem um norte escolhido, a preguiça te leva ao lugar de sempre.",
  "Todo dia largado é chão cedido ao caos sem luta.",
  "Amor próprio que não vira ação é só conversa bonita com o espelho.",
  "Você não domina o dia. Você o honra e vai para o próximo.",
  "A vida de quem você admira foi comprada com moedas que você ainda guarda com medo de gastar.",
  "Não há cova tão funda que a repetição paciente do bem não comece a preencher.",
  "Aquilo que você tolera vira o padrão. E o padrão vira a sua vida.",
  "Mire no impossível de perto para acertar o difícil de longe.",
  "Você é o adulto encarregado da criança que foi. Não a abandone de novo.",
  "Disciplina é o que sobra do amor próprio depois que as palavras acabam.",
  "Não pergunte por que dói. Pergunte no que você se transforma aguentando.",
  "O começo cobra ousadia. A continuação cobra caráter. Pague as duas.",
  "Você não precisa confiar no fim. Só não sabotar o meio.",
  "Mudança de verdade é monótona por fora e sísmica por dentro.",
  "O que você empurra com medo, você recolhe com vergonha e correção monetária.",
  "Ordene o pequeno com perfeição. O grande se enfrenta a partir daí.",
  "Você não é feito de planos. É feito de quartas-feiras cumpridas.",
  "A sua melhor versão observa calada toda vez que você escolhe o caminho torto e curto.",
  "Não corra do peso. É o peso que te faz caber na vida que você quer.",
  "Quem não decide fica à mercê de quem decidiu. Decida.",
  "São noventa dias para lembrar a si mesmo que promessa sua não é enfeite.",
  "A estrada da mudança é apertada, subida e deserta. Suba mesmo assim.",
  "O objetivo não é a queda zero. É o abandono zero.",
  "O sentido que falta na sua vida está trancado no cômodo que você não quer abrir.",
  "Você não precisa de mais teoria. Precisa parar de fugir da prática.",
  "A ordem que você semeia por dentro é a única que o caos não pisoteia.",
  "Cada dia marcado é palavra cumprida com o homem ou a mulher que você quer ser.",
  "A vida é sua para escrever. Ninguém mais vai segurar essa caneta por você.",
  "Você já testou o mínimo esforço. Rendeu o mínimo de vida. Teste o oposto.",
  "Vida plena não é a sem feras. É a de quem virou caçador.",
  "O fardo que você joga fora hoje aterrissa amanhã, mais pesado, no seu colo.",
  "Você não deve grandeza ao mundo. Deve honestidade a si mesmo, e ela começa hoje.",
  "O medo de tentar nunca supera o remorso de nunca ter tentado.",
  "Empolgação é bônus. Constância é obrigação.",
  "Quem transforma a própria vida enjoa da repetição bem antes de largá-la.",
  "O que você faz no dia em que tudo dá errado decide o tamanho do seu melhor dia.",
  "Não fique esperando o jogo ficar justo para você entrar forte nele.",
  "Sua verdade cabe nos seus últimos sete dias. Encare-os sem desviar o olhar.",
  "Não precisa de coragem para tudo. Só para a próxima hora.",
  "A mudança acontece quando ficar parado passa a doer mais do que se mexer.",
  "Toda vida admirável foi, primeiro, uma teimosia diária que ninguém aplaudiu.",
  "O caos não avisa. Que ele te ache de pé.",
  "Aponte para o mais alto e observe o resto se organizar por gravidade.",
  "Você responde pelo que faz e pelo que deixa criar raiz.",
  "A disciplina de agora é o sossego de daqui a doze meses.",
  "É difícil, sim. Também é o único caminho que leva onde você quer.",
  "Você não vira outra pessoa. Você para de negar a que sempre esteve aí dentro.",
  "O esforço que ninguém vê hoje é o resultado que ninguém contesta depois.",
  "Não cobre a vida. Entregue algo a ela primeiro.",
  "Rotina é a forma mais barata de pagar pela pessoa que você quer ser.",
  "O caos de fora só quebra quem não ergueu estrutura por dentro.",
  "Carregue até a bagunça que não foi você que fez. É assim que se ganha comando sobre a própria vida.",
  "Não espere a enchente para checar se o dique aguenta.",
  "Mentira para si mesmo é a única cela sem chave.",
  "Sua transformação não precisa de assinatura de ninguém.",
  "O que você rega, cresce. O que você negligencia, seca. Escolha a plantação.",
  "A vida sobe o degrau na medida do seu tamanho. Cresça em vez de reclamar.",
  "Todo salto real acontece no lado desconfortável da decisão.",
  "Pare de assistir. O filme da sua vida está rodando agora.",
  "O corajoso também trava. A diferença está no que ele faz logo depois.",
  "Sem direção escolhida, você sempre volta ao ponto de partida.",
  "Dia sem esforço é terra entregue ao inimigo sem um tiro.",
  "Amor próprio de verdade tem calo na mão.",
  "Você não conquista o dia. Você o cumpre com honra.",
  "A vida que te dá inveja foi comprada com o preço que você ainda acha caro demais.",
  "Não há abismo que a repetição serena do bem não comece a fechar.",
  "O que você aceita como normal define o teto de tudo.",
  "Mire longe demais para ter chance de acertar longe o suficiente.",
  "Você cuida do adulto que a criança de ontem virou. Não desista dela agora.",
  "Disciplina é amor próprio que já não precisa de discurso.",
  "Não pergunte por que pesa. Pergunte quem emerge de baixo do peso.",
  "Começar pede audácia. Continuar pede espinha. Tenha as duas.",
  "Você não precisa acreditar no desfecho. Só se recusar a sabotar o percurso.",
  "Transformação verdadeira é tediosa por fora e tectônica por dentro.",
  "O que você adia com medo, você paga com vergonha, e a vergonha rende juros.",
  "Organize o pequeno com esmero. É desse chão que se encara o grande.",
  "Você não é seus planos. É suas segundas-feiras cumpridas.",
  "Sua melhor versão está sentada aí, calada, vendo você escolher o atalho ruim de novo.",
  "Não recue do peso. É ele que te encaixa na vida que você diz querer.",
  "Quem não decide serve ao projeto de quem decidiu. Decida você.",
  "São noventa dias para relembrar que a sua palavra não é decoração.",
  "A trilha da mudança é estreita, em aclive e sem torcida. Suba assim mesmo.",
  "A meta não é zero falha. É zero desistência.",
  "O sentido que falta está atrás da porta que você jura que vai abrir amanhã.",
  "Você não precisa de mais um livro. Precisa executar o que o primeiro já disse.",
  "A ordem que você constrói por dentro é a única que o caos não invade.",
  "Cada quadrado preenchido é uma promessa honrada com quem você quer ser.",
  "A história é sua. A caneta, também. Escreva.",
  "Você já rodou a versão folgada da sua vida. Rendeu pouco. Rode a versão exigente.",
  "Vida cheia não é a sem monstros. É a de quem aprendeu a domá-los.",
  "O fardo que você descarta hoje volta amanhã mais pesado e endereçado a você.",
  "Você não deve heroísmo ao mundo. Deve verdade a si mesmo, e o prazo é hoje.",
  "O medo de arriscar nunca dói tanto quanto o luto de nunca ter arriscado.",
  "Ânimo é presente. Regularidade é dever.",
  "Quem muda a vida cansa da repetição, e mesmo cansado, repete.",
  "O que você faz no pior dia mede o teto do seu melhor.",
  "Não fique de fora esperando o jogo ficar limpo.",
  "Sua verdade está nos últimos sete dias. Olhe sem piedade e sem desvio.",
  "Coragem para a hora seguinte já basta.",
  "A mudança começa no ponto exato em que a inércia fica mais cara que o movimento.",
  "Toda biografia impressionante começou como rotina que ninguém filmou.",
  "O caos entra sem bater. Fique em pé.",
  "Aponte para o topo e deixe a força da mira arrumar o resto.",
  "Você é responsável pelo que faz e pelo que consente em repetir.",
  "A disciplina de hoje é a consciência tranquila do próximo ano.",
  "Vai custar. E, ainda assim, é o único trajeto que chega lá.",
  "Você não troca de pessoa. Você para de mentir sobre quem sempre foi.",
  "O suor que ninguém registra hoje é o número que ninguém discute depois.",
  "Não faça exigências à vida. Faça entregas.",
  "Rotina é a hipoteca mais barata da pessoa que você quer se tornar.",
  "O caos externo só derruba quem não fincou pilar por dentro.",
  "Assuma até a desordem alheia. É o pedágio do domínio sobre a própria vida.",
  "Não espere o temporal para testar o telhado.",
  "Iludir a si mesmo é a única armadilha sem saída.",
  "Ninguém precisa carimbar a sua mudança.",
  "O que recebe água, brota. O que fica no seco, morre. Escolha o canteiro.",
  "A vida ergue a barra junto com você. Suba a barra crescendo, não abaixando.",
  "O salto verdadeiro só existe no lado incômodo da escolha.",
  "Largue a arquibancada. O jogo da sua vida é agora e você está no banco por opção.",
  "O bravo também congela. Ele só descongela mais rápido.",
  "Sem norte, todo vento te empurra para o mesmo canto de sempre.",
  "Cada dia sem luta é palmo de terreno dado ao caos de graça.",
  "Amor próprio que não caleja a mão não passa de retórica de espelho.",
  "Você não vence o dia. Você o cumpre com dignidade.",
  "A vida invejada tem preço, e o preço são as moedas que você ainda esconde com medo.",
  "Não existe fosso que o bem repetido, dia após dia, não comece a aterrar.",
  "O que você normaliza vira o horizonte máximo da sua vida.",
  "Mire absurdamente alto para acertar razoavelmente longe.",
  "Você é o zelador da criança que foi. Não a largue justo agora.",
  "Disciplina é o amor próprio depois que ele para de precisar de plateia.",
  "Não questione o peso. Questione quem você vira carregando.",
  "O primeiro passo pede ousadia. O centésimo pede honra. Pague os dois.",
  "Você não precisa de fé no resultado. Só de fidelidade ao processo.",
  "Mudar de vida é entediante por fora e revolucionário por dentro.",
  "O que você empurra por covardia, você resgata por vergonha, com multa.",
  "Ajuste o pequeno até ficar impecável. O grande se encara a partir do pequeno.",
  "Você não é intenção. É repetição.",
  "Sua melhor versão está te olhando escolher o caminho fácil pela milésima vez.",
  "Não fuja do fardo. É ele que te dá densidade.",
  "Quem não decide entrega o volante. Segure o seu.",
  "Noventa dias para você lembrar que promessa sua tem que valer.",
  "O caminho é estreito, em subida e sem público. É por ali mesmo.",
  "O alvo não é nunca errar. É nunca abandonar.",
  "O sentido some quando você recusa toda responsabilidade que poderia ter carregado.",
  "Você não precisa de novo método. Precisa de velha teimosia.",
  "A ordem interior é a fortaleza que nenhuma tempestade externa invade.",
  "Cada marca no calendário é palavra mantida com o seu eu de amanhã.",
  "A caneta da sua história está na sua mão. Pare de esperar que outro escreva.",
  "Você já viveu no modo econômico. Rendeu uma vida econômica. Mude o modo.",
  "Vida grande não é a sem dragões. É a de quem virou o dono da espada.",
  "O peso que você abandona hoje reaparece amanhã, maior, com o seu nome nele.",
  "Você não deve o extraordinário ao mundo. Deve o verdadeiro a si mesmo, e vence hoje.",
  "Temer o começo dói menos que velar o que nunca começou.",
  "Motivação é cortesia. Consistência é contrato.",
  "Quem transforma a vida se cansa da rotina e continua nela.",
  "O seu pior dia mostra do que a sua melhor versão é capaz.",
  "Não espere o campo nivelar para jogar sério.",
  "A sua verdade está nos últimos sete dias. Olhe de frente.",
  "Coragem só para a próxima hora já resolve.",
  "A virada começa quando parar custa mais que seguir.",
  "Toda trajetória admirável foi antes uma insistência sem holofote.",
  "O caos não pede licença para entrar. Não peça licença para reagir.",
  "Aponte para o cume e deixe a inclinação da mira endireitar o caminho.",
  "Você responde pelo que faz e pelo que aceita transformar em costume.",
  "A disciplina de agora é a paz de espírito do ano que vem.",
  "Custa caro. E mesmo assim é o único trajeto que leva ao lugar certo.",
  "Você não se torna outro. Você se torna, finalmente, inteiro.",
  "O esforço anônimo de hoje é o resultado inegociável de amanhã.",
  "Pare de faturar da vida. Comece a depositar nela.",
  "Rotina é a forma mais acessível de comprar quem você quer ser.",
  "O caos de fora só rompe quem não levantou parede por dentro.",
  "Carregue até o que estragaram por você. É assim que a vida vira sua.",
  "Não espere o incêndio para conferir se o extintor funciona.",
  "Se enganar é a única cilada de onde não se escapa.",
  "A sua mudança dispensa autorização de terceiros.",
  "O que é regado vinga. O que é largado seca. Cuide da lavoura certa.",
  "A vida sobe o nível conforme você sobe. Suba você.",
  "O avanço fica sempre no lado desconfortável da escolha.",
  "Saia da plateia. A sua vida é o jogo, e você está de fora por escolha.",
  "O corajoso hesita igual. Ele só decide mais rápido depois.",
  "Sem direção definida, você orbita para sempre o mesmo ponto.",
  "Dia sem batalha é chão cedido ao caos sem resistência.",
  "Amor próprio que não vira suor é só slogan.",
  "Você não domina o dia. Você o cumpre com respeito.",
  "A vida que você cobiça custa moedas que você ainda tem medo de tirar do bolso.",
  "Não há cratera que a repetição paciente do bem não comece a fechar.",
  "O que você deixa passar hoje vira o padrão de amanhã.",
  "Mire alto demais para acertar alto o bastante.",
  "Você cuida do adulto em que a sua criança se tornou. Não a abandone agora.",
  "Disciplina é o amor próprio que já não fala, só faz.",
  "Não discuta o peso. Descubra quem você vira sob ele.",
  "Começar exige coragem. Insistir exige caráter. Traga os dois.",
  "Você não precisa apostar no final. Só não trair o caminho.",
  "Mudar de vida é monótono por fora, terremoto por dentro.",
  "O que você adia por medo volta como fatura de vergonha, com correção.",
  "Deixe o pequeno impecável. Do pequeno se enfrenta o resto.",
  "Você não é o que planejou. É o que repetiu.",
  "A sua melhor versão assiste, em silêncio, você pegar o atalho de novo.",
  "Não recue diante do fardo. É ele que te dá forma.",
  "Quem não escolhe é escolhido. Escolha primeiro.",
  "Noventa dias para provar que a sua palavra não é fumaça.",
  "A subida da mudança é estreita, íngreme, vazia. Suba do mesmo jeito.",
  "O objetivo não é o acerto perfeito. É a permanência.",
  "O sentido que você perdeu está guardado atrás do que você evita.",
  "Você não precisa de outra estratégia. Precisa executar a que tem sem dó de si.",
  "A ordem que você funda por dentro é a única inexpugnável.",
  "Cada dia riscado é um pacto honrado com quem você pretende ser.",
  "A história é sua e a caneta também. Deixe de esperar por um ghost-writer.",
  "Você já testou o esforço mínimo. Colheu o mínimo. Teste o máximo.",
  "Vida robusta não é a sem feras. É a de quem virou o predador.",
  "O peso descartado hoje volta amanhã, maior, com etiqueta de entrega no seu nome.",
  "Você não deve façanha ao mundo. Deve sinceridade a si mesmo, e o prazo venceu.",
  "Recear o início machuca menos que chorar o que nunca nasceu.",
  "Empolgação é gentileza. Regularidade é palavra empenhada.",
  "Quem vira a própria vida enjoa da repetição e insiste mesmo enjoado.",
  "O que você faz no dia em que nada colabora define o teto do seu melhor.",
  "Não espere o campo ficar plano para jogar de verdade.",
  "A sua verdade está nesses últimos sete dias. Encare sem piscar.",
  "Coragem só para as próximas horas basta e sobra.",
  "A guinada acontece quando ficar parado passa a arder mais do que andar.",
  "Toda vida que impressiona foi antes teima diária sem plateia.",
  "O caos arromba a porta. Você não precisa de licença para revidar.",
  "Aponte para o alto e deixe a mira consertar o rumo.",
  "Você responde pelo que faz e pelo que consente virar hábito.",
  "A disciplina de hoje é a serenidade de daqui a doze meses.",
  "Vai pesar. E é, ainda assim, o único caminho que dá certo.",
  "Você não vira outra pessoa. Você deixa de fingir que não é essa.",
  "O trabalho que ninguém filma hoje é o número que ninguém rebate amanhã.",
  "Pare de cobrar a vida. Comece a alimentá-la.",
  "Rotina é o preço de banana da pessoa que você quer ser.",
  "O caos externo só destrói quem não ergueu coluna interna.",
  "Segure até o peso que puseram nas suas costas sem você pedir. É assim que a vida vira sua.",
  "Não espere a cheia para ver se a represa presta.",
  "Mentir para si é a única jaula sem porta.",
  "A sua transformação não precisa de carimbo.",
  "O regado brota. O abandonado seca. Escolha o que quer colher.",
  "A régua sobe com você. Suba com ela, não fuja dela.",
  "O crescimento mora do lado desconfortável de cada escolha.",
  "Deixe a plateia. A sua vida é a partida e você está no banco de reservas por opção.",
  "O valente também trava. Ele só destrava antes.",
  "Sem norte, você sempre reencontra a mesma parede.",
  "Dia sem esforço é fronteira cedida ao caos de graça.",
  "Amor próprio sem ação é conversa fiada com o reflexo.",
  "Você não conquista o dia. Você o cumpre com honra e vai adiante.",
  "A vida que dá inveja cobra as moedas que você ainda guarda com medo.",
  "Nenhum poço é fundo demais para a repetição paciente do bem não começar a preencher.",
  "O que você tolera vira o teto. E o teto vira a vida.",
  "Mire longe demais para chegar longe o suficiente.",
  "Você é o guardião da criança que foi. Não a solte agora.",
  "Disciplina é amor próprio sem legenda.",
  "Não discuta o porquê do peso. Note quem sai de baixo dele.",
  "O início pede ousadia; a insistência, honra. Pague as duas.",
  "Você não precisa acreditar no fim. Só não abandonar o meio.",
  "Mudança que fica é chata por fora e sísmica por dentro.",
  "O adiado por medo retorna como conta de vergonha, corrigida.",
  "Deixe o pequeno redondo. É dele que se encara o grande.",
  "Você não é o que jurou fazer. É o que fez de novo.",
  "A sua melhor versão te observa escolher o caminho torto pela enésima vez.",
  "Não fuja do fardo. É ele que te dá contorno.",
  "Quem não decide vira peça do plano alheio. Faça o seu.",
  "Noventa dias para lembrar que promessa sua tem lastro.",
  "A trilha é apertada, em aclive, sem torcida. É por ela.",
  "A meta não é zerar o erro. É não zerar a presença.",
  "O sentido perdido está atrás daquilo que você não quer encarar.",
  "Você não precisa de plano novo. Precisa cumprir o antigo sem pena.",
  "A ordem que você planta por dentro é a fortaleza que o caos não toma.",
  "Cada dia assinalado é acordo honrado com o seu eu de amanhã.",
  "A caneta da sua vida está na sua mão. Escreva você.",
  "Você já viveu no mínimo. Rendeu o mínimo. Viva no exigente.",
  "Vida ampla não é a sem dragões. É a de quem afiou a lâmina.",
  "O peso jogado fora hoje volta amanhã maior, endereçado a você.",
  "Você não deve grandeza ao mundo. Deve verdade a si, e a fatura venceu.",
  "O medo de tentar cabe no bolso. O luto do que não foi tentado, não.",
  "Ânimo é bônus. Constância é cláusula.",
  "Quem transforma a vida cansa da repetição e continua nela até cansar dela também.",
  "O que você faz no dia mais difícil da semana define o alcance da sua melhor versão.",
  "Não espere o mundo nivelar o gramado para você entrar de verdade.",
  "A sua verdade está nos últimos sete dias. Encare sem álibi.",
  "Basta coragem para a próxima hora.",
  "A virada nasce quando permanecer igual passa a doer mais que se mover.",
  "Toda vida admirável foi, primeiro, insistência sem holofote.",
  "O caos não toca a campainha. Não peça licença para reagir.",
  "Aponte para o topo e deixe a mira corrigir o percurso.",
  "Você responde pelo que faz e pelo que deixa criar raiz em você.",
  "A disciplina de hoje é a paz do ano que vem.",
  "Vai ser pesado. E é o único caminho que leva onde você quer.",
  "Você não se torna outra pessoa. Você para de trair a que já é.",
  "O esforço que ninguém vê hoje é o resultado que ninguém nega amanhã.",
  "Pare de exigir da vida. Passe a entregar para ela.",
  "Rotina é a forma mais barata de pagar por quem você quer ser.",
  "O caos de fora só quebra quem não construiu por dentro.",
  "Carregue até a bagunça que herdou. É assim que a vida passa a ser sua.",
  "Não espere o dilúvio para testar a arca.",
  "Enganar a si mesmo é a única cela de onde ninguém sai.",
  "A sua mudança não pede autorização.",
  "O que é regado cresce. O que é esquecido murcha. Escolha a horta.",
  "A régua sobe junto com você. Prefira crescer a rebaixá-la.",
  "O progresso está do lado incômodo de toda decisão.",
  "Desça da arquibancada. A sua vida acontece no campo.",
  "O corajoso trava como qualquer um. Ele só age antes de descongelar.",
  "Sem direção, você faz o mesmo círculo a vida inteira.",
  "Dia sem esforço é território cedido ao caos sem troco.",
  "Amor próprio que não sua é só letra de música.",
  "Você não conquista o dia. Você o honra e segue.",
  "A vida invejada tem preço, e o preço são moedas guardadas por medo.",
  "Não há abismo que a repetição serena do bem não comece a fechar.",
  "O que você aceita como normal vira o teto de tudo que você terá.",
  "Aponte alto demais para acertar alto o bastante.",
  "Você é o responsável pelo adulto que a sua criança virou.",
  "Disciplina é amor próprio em silêncio.",
  "Não pergunte por que dói. Pergunte quem você vira ao aguentar.",
  "Começar exige coragem. Continuar exige espinha dorsal.",
  "Você não precisa apostar no resultado. Só honrar o processo.",
  "Mudar é monótono por fora e vulcânico por dentro.",
  "O adiado por covardia volta como vergonha com juros compostos.",
  "Deixe o pequeno perfeito. É dele que se salta para o grande.",
  "Você é o que repete, não o que promete.",
  "A sua melhor versão te vê pegar o atalho de novo, e não diz nada.",
  "Não recue do fardo. É ele que te dá densidade e direção.",
  "Quem não decide é decidido. Decida.",
  "Noventa dias para provar que a sua palavra tem peso.",
  "O caminho é estreito, subida e solidão. Suba mesmo assim.",
  "O objetivo não é a perfeição. É a permanência.",
  "O sentido está trancado no cômodo que você jura abrir amanhã.",
  "Você não precisa de outro livro. Precisa aplicar o primeiro.",
  "A ordem interna é a única muralha que o caos não escala.",
  "Cada dia marcado é uma promessa cumprida com quem você quer se tornar.",
  "A história é sua. Pegue a caneta.",
  "Você já viveu economizando esforço. Colheu uma vida econômica.",
  "Vida cheia não é a sem monstros. É a de quem os enfrenta.",
  "O fardo largado hoje cai amanhã, maior, no seu colo.",
  "Você não deve heroísmo ao mundo. Deve honestidade a si, hoje.",
  "O medo de começar é leve perto do peso de nunca ter tentado.",
  "Motivação é presente. Disciplina é palavra dada.",
  "Quem muda a vida enjoa da repetição e repete mesmo assim.",
  "O que você faz no pior dia mede o tamanho do seu melhor.",
  "Não espere o mundo ficar justo para você ficar firme.",
  "A verdade sobre você está nos seus últimos sete dias.",
  "Coragem para a hora seguinte já é suficiente.",
  "A mudança começa quando parar dói mais que continuar.",
  "Toda vida notável foi teimosia diária antes de ser história.",
  "O caos entra sem pedir. Reaja sem pedir.",
  "Mire no ponto mais alto e deixe o resto se alinhar.",
  "Você responde pelo que faz e pelo que vira rotina em você.",
  "A disciplina de hoje é a tranquilidade de amanhã.",
  "Vai custar caro. É o único preço que compra a vida certa.",
  "Você não vira outra pessoa. Você vira quem sempre pôde ser.",
  "O trabalho invisível de hoje é o resultado visível de amanhã.",
  "Pare de cobrar. Comece a entregar.",
  "Rotina compra, barato, a pessoa que você quer ser.",
  "O caos externo só derruba quem está oco por dentro.",
  "Carregue até o que não foi você que quebrou.",
  "Não espere a tempestade para reforçar o teto.",
  "Mentira para si mesmo é a única prisão perpétua.",
  "Sua transformação não precisa da assinatura de ninguém.",
  "O que rega, cresce. O que abandona, seca.",
  "A régua sobe com o seu tamanho. Cresça.",
  "O avanço está sempre no lado desconfortável.",
  "Saia da plateia e entre no jogo da sua vida.",
  "O bravo hesita. Ele só decide mais rápido.",
  "Sem norte, todo caminho te devolve ao começo.",
  "Dia parado é terreno dado ao caos.",
  "Amor próprio sem ação é discurso vazio.",
  "Você cumpre o dia, não o vence.",
  "A vida que você inveja custou o que você ainda não pagou.",
  "Nenhum poço vence a repetição paciente do bem.",
  "O que você tolera vira o seu teto.",
  "Mire alto demais para acertar longe.",
  "Você é o guardião da criança que foi.",
  "Disciplina é amor próprio que virou hábito.",
  "Não pergunte por que pesa. Pergunte quem você vira.",
  "Começar pede coragem. Seguir pede caráter.",
  "Você não precisa acreditar no fim. Só não largar o meio.",
  "Mudar de verdade é chato por fora, sísmico por dentro.",
  "O adiado volta como vergonha, com juros.",
  "Deixe o pequeno impecável antes de encarar o grande.",
  "Você é repetição, não intenção.",
  "A sua melhor versão observa, calada, cada atalho seu.",
  "Não recue do peso. Ele te dá forma.",
  "Quem não decide é levado. Decida.",
  "Noventa dias para a sua palavra valer algo.",
  "O caminho é estreito e sem plateia. Trilhe.",
  "A meta é não desistir, não é não errar.",
  "O sentido está atrás do que você evita.",
  "Você não precisa de plano novo. Precisa executar.",
  "A ordem interna é a muralha que segura o caos.",
  "Cada dia riscado é uma promessa honrada.",
  "A caneta da sua vida é sua. Escreva.",
  "Você já viveu no mínimo. Viva no exigente.",
  "Vida grande é a de quem enfrenta os dragões.",
  "O fardo largado hoje volta maior amanhã.",
  "Você deve verdade a si mesmo, e vence hoje.",
  "O medo de tentar é pequeno perto do remorso.",
  "Constância é dever. Ânimo é bônus.",
  "Quem transforma a vida repete mesmo enjoado.",
  "O pior dia mede o seu melhor.",
  "Não espere o jogo ficar justo.",
  "A sua verdade está nos últimos sete dias.",
  "Coragem para a próxima hora basta.",
  "A virada começa quando parar dói mais.",
  "Toda vida notável foi teimosia sem holofote.",
  "O caos não bate. Reaja sem licença.",
  "Mire no topo. O resto se alinha.",
  "Você responde pelo que vira hábito em você.",
  "A disciplina de hoje é a paz de amanhã.",
  "Vai pesar, e é o único caminho.",
  "Você vira quem sempre pôde ser.",
  "O invisível de hoje é o inegável de amanhã.",
  "Pare de cobrar a vida. Entregue.",
  "Rotina compra barato a sua melhor versão.",
  "O caos só quebra quem está oco.",
  "Carregue até o que não foi você.",
  "Não espere a tempestade para reforçar a base.",
  "Mentir para si é prisão sem porta.",
  "A sua mudança dispensa carimbo.",
  "O que rega cresce; o que larga seca.",
  "A régua sobe com você. Suba.",
  "O avanço está no lado desconfortável.",
  "Entre no jogo da sua vida.",
  "O bravo decide mais rápido, só isso.",
  "Sem norte, você orbita o começo.",
  "Dia parado é chão dado ao caos.",
  "Amor próprio sem ação é slogan.",
  "Você cumpre o dia com honra.",
  "A vida invejada custou o que você não pagou.",
  "A repetição paciente do bem vence qualquer poço.",
  "O que você tolera vira teto.",
  "Mire alto demais para acertar o suficiente.",
  "Você guarda a criança que foi.",
  "Disciplina é amor próprio em ação.",
  "Pergunte quem você vira sob o peso.",
  "Seguir pede caráter.",
  "Não largue o meio.",
  "Mudar é chato por fora, revolução por dentro.",
  "O adiado cobra vergonha com juros.",
  "Impecável no pequeno, pronto para o grande.",
  "Você é o que repete.",
  "A sua melhor versão te vê escolher o atalho.",
  "O peso te dá forma. Não recue.",
  "Quem não decide é decidido.",
  "Noventa dias para a palavra valer.",
  "Estreito e sem plateia: é por ali.",
  "Não desistir é a meta.",
  "O sentido está atrás do que você foge.",
  "Execute o plano que já tem.",
  "A ordem interna segura o caos.",
  "Dia riscado, promessa honrada.",
  "Sua vida, sua caneta.",
  "Saia do mínimo.",
  "Enfrente os dragões.",
  "O fardo largado volta maior.",
  "Verdade a si mesmo, hoje.",
  "O remorso pesa mais que o risco.",
  "Constância é contrato.",
  "Repita mesmo enjoado.",
  "O pior dia mostra o seu teto.",
  "Não espere justiça no jogo.",
  "Últimos sete dias: essa é a sua verdade.",
  "Só a próxima hora precisa de coragem.",
  "Parar vai doer mais. Continue.",
  "Teimosia sem holofote vira história.",
  "O caos não avisa. Nem você.",
  "Topo na mira, resto no lugar.",
  "Você é o hábito que alimenta.",
  "Disciplina hoje, paz amanhã.",
  "Pesa, e é o caminho.",
  "Vire quem você pode ser.",
  "Invisível hoje, inegável amanhã.",
  "Entregue à vida, não cobre.",
  "Rotina é a sua melhor versão em oferta.",
  "Oco por dentro, o caos vence.",
  "Carregue o que herdou.",
  "Reforce a base antes da chuva.",
  "Mentira interna: cadeia perpétua.",
  "Mudança sem carimbo.",
  "Regue o que quer colher.",
  "A barra sobe. Suba junto.",
  "Desconforto é a direção.",
  "No campo, não na arquibancada.",
  "Decide rápido: é o que o bravo faz.",
  "Sem norte, sempre o mesmo círculo.",
  "Dia parado, caos avançado.",
  "Ação, não slogan.",
  "Cumpra o dia com honra.",
  "O preço da vida invejada é o que você poupa por medo.",
  "Poço nenhum resiste ao bem repetido.",
  "Teto é o que você tolera.",
  "Alto demais para acertar longe.",
  "Zele pela criança que foi.",
  "Amor próprio que faz, não que fala.",
  "Quem emerge do peso é você.",
  "Caráter sustenta o seguir.",
  "O meio não se larga.",
  "Chato fora, terremoto dentro.",
  "Adiar hoje, pagar vergonha depois.",
  "Pequeno redondo, grande possível.",
  "Repetição te define.",
  "Ela te vê no atalho. Não pegue.",
  "Forma vem do peso.",
  "Não decidir é uma decisão pior.",
  "Noventa dias de palavra cumprida.",
  "Trilha vazia, caminho certo.",
  "Meta: presença, não perfeição.",
  "Sentido mora atrás do medo.",
  "O plano velho, bem feito.",
  "Muralha interna contra o caos.",
  "Marca no dia, pacto mantido.",
  "Escreva a própria história.",
  "Fora do modo econômico.",
  "Dragão é para enfrentar.",
  "Solte o fardo e ele volta dobrado.",
  "Honestidade consigo, agora.",
  "Arrepender custa mais que arriscar.",
  "Contrato: comparecer todo dia.",
  "Enjoou? Repita mesmo assim.",
  "Seu pior dia dita seu teto.",
  "O jogo não vai ficar justo.",
  "Olhe seus últimos sete dias.",
  "Coragem por uma hora.",
  "Continuar dói menos que parar.",
  "Sem plateia, vira lenda.",
  "Aja sem pedir licença ao caos.",
  "Mira no alto, vida no eixo.",
  "Você é o que virou costume.",
  "Hoje disciplina, amanhã sossego.",
  "É pesado e é o caminho.",
  "Torne-se quem você poderia ser.",
  "O anônimo de hoje prova o de amanhã.",
  "Deposite na vida.",
  "Rotina: sua melhor versão a preço de custo.",
  "Vazio por dentro, o caos entra.",
  "Assuma o que caiu no seu colo.",
  "Alicerce antes do temporal.",
  "Autoengano não tem fiança.",
  "Mudar não precisa de aval.",
  "Colhe quem rega.",
  "A régua acompanha o seu crescimento.",
  "O incômodo aponta o caminho.",
  "Jogue, não assista.",
  "Bravura é decidir rápido.",
  "Sem rumo, mesmo lugar sempre.",
  "Parou um dia, cedeu terreno.",
  "Faça, não fale.",
  "Honre o dia.",
  "O que você inveja custou coragem que faltou a você.",
  "Repetição paciente esvazia qualquer poço.",
  "Sua tolerância é o seu limite.",
  "Aponte além para chegar perto.",
  "Proteja quem você foi.",
  "Disciplina é o amor próprio dos fortes.",
  "Do peso nasce quem você será.",
  "Persistir é caráter em movimento.",
  "Do meio ninguém te tira.",
  "Fora tédio, dentro revolução.",
  "Medo hoje, boleto de vergonha amanhã.",
  "Domine o pequeno.",
  "Repetiu, virou você.",
  "Ela observa cada desvio seu.",
  "Peso molda. Encare.",
  "Não decidir entrega o leme.",
  "Noventa provas de que você cumpre o que fala.",
  "Sozinho na subida: siga.",
  "Fique. Não precisa vencer, precisa ficar.",
  "O que você foge guarda o seu sentido.",
  "Menos plano, mais execução.",
  "Erga a muralha por dentro.",
  "Cada dia, um voto em quem você quer ser.",
  "A caneta é sua. Use.",
  "Chega de viver no talo mínimo.",
  "Vá caçar o dragão.",
  "O fardo abandonado te encontra amanhã.",
  "Diga a verdade a si mesmo, hoje, sem rodeio.",
  "Arrependimento é o juro do medo.",
  "Assinou o contrato ao decidir mudar. Compareça.",
  "Cansou da rotina? Ótimo sinal. Continue.",
  "Seu pior dia é o gabarito do seu melhor.",
  "O jogo é torto. Jogue melhor.",
  "Seus últimos sete dias não mentem.",
  "Só a próxima hora exige coragem.",
  "Continuar é mais barato que recomeçar do zero pela décima vez.",
  "Sem holofote, a insistência vira destino.",
  "O caos não bate na porta. Você também não precisa.",
  "Alvo no topo. O resto obedece à gravidade.",
  "Você é a soma dos seus hábitos, não das suas frases.",
  "A disciplina de hoje assina a paz de amanhã.",
  "É para pesar. É por isso que funciona.",
  "Deixe de adiar a pessoa que você poderia ser.",
  "O que ninguém vê hoje é o que ninguém nega depois.",
  "Alimente a vida antes de cobrar dela um retorno.",
  "A rotina entrega, no boleto mais barato, a sua melhor versão.",
  "O caos só arromba quem não trancou nada por dentro.",
  "Segure o peso que puseram em você sem pedir licença.",
  "Cheque a fundação antes que o chão trema.",
  "Da mentira consigo mesmo não há liberdade condicional.",
  "Ninguém precisa liberar a sua mudança.",
  "Você colhe o que rega e enterra o que abandona.",
  "A régua sobe no seu ritmo. Não abaixe: cresça.",
  "Todo salto real dói no lado de dentro da decisão.",
  "Levante da arquibancada da sua própria vida.",
  "O corajoso sente o mesmo frio na barriga. Só age antes.",
  "Sem um norte, você reencontra a mesma parede a vida toda.",
  "Cada dia sem luta é um palmo de chão dado ao caos.",
  "Amor próprio que não vira suor é só barulho.",
  "Você não vence o dia. Você o honra e vai para o próximo.",
];
